apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nginx-kubernetes-gateway.fullname" . }}
  # Now the namespace must be nginx-gateway
  namespace: nginx-gateway
  labels:
    {{- include "nginx-kubernetes-gateway.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "nginx-kubernetes-gateway.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nginx-kubernetes-gateway.selectorLabels" . | nindent 8 }}
    spec:
      shareProcessNamespace: true
      serviceAccountName: nginx-gateway
      volumes:
        - name: nginx-config
          emptyDir: { }
        - name: var-lib-nginx
          emptyDir: { }
        - name: njs-modules
          configMap:
            name: njs-modules
      initContainers:
        - image: busybox:1.34 # FIXME(pleshakov): use gateway container to init the Config with proper main config
          name: nginx-config-initializer
          command: [ 'sh', '-c', 'echo "load_module /usr/lib/nginx/modules/ngx_http_js_module.so; events {}  pid /etc/nginx/nginx.pid; http { include /etc/nginx/conf.d/*.conf; js_import /usr/lib/nginx/modules/njs/httpmatches.js; }" > /etc/nginx/nginx.conf && mkdir /etc/nginx/conf.d /etc/nginx/secrets && chown 1001:0 /etc/nginx/conf.d /etc/nginx/secrets' ]
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx
      containers:
        - image: {{ .Values.image.nginxGateway.repository }}:{{ .Values.image.nginxGateway.tag }}
          imagePullPolicy: {{ .Values.image.nginxGateway.pullPolicy }}
          name: nginx-gateway
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx
          securityContext:
            runAsUser: 1001
            # FIXME(pleshakov) - figure out which capabilities are required
            # dropping ALL and adding only CAP_KILL doesn't work
            # Note: CAP_KILL is needed for sending HUP signal to NGINX main process
          args:
            - --gateway-ctlr-name={{.Values.gatewayClass.controllerName}}
            - --gatewayclass={{.Values.gatewayClass.name}}
        - image: {{ .Values.image.nginx.repository }}:{{ .Values.image.nginx.tag }}
          imagePullPolicy: {{ .Values.image.nginx.pullPolicy }}
          name: nginx
          ports:
            - name: http
              containerPort: 80
            - name: https
              containerPort: 443
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx
            - name: var-lib-nginx
              mountPath: /var/lib/nginx
            - name: njs-modules
              mountPath: /usr/lib/nginx/modules/njs
